#!/usr/bin/env python3
import subprocess, shlex, re

def x(c): return subprocess.Popen(shlex.split(c), stdout=subprocess.PIPE)

def getifgate():
  p=x("route -n")
  for l in p.stdout.readlines()[2:]:
    s=l.decode().split()
    if s[1]!=b"0.0.0.0":
      return str(s[1]), str(s[7])

def setup(port=8100):
  f=open('/proc/sys/net/ipv4/ip_forward',"w")
  f.write("1")
  f.close()
  x("iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port " + str(port))

def clean():
  f=open('/proc/sys/net/ipv4/ip_forward',"w")
  f.write("0")
  f.close()
  x("iptables --flush")

port=8100
ps={}

while True:
  gate, iface = getifgate()
  setup(port)
  ps['ssls']=x('xterm -e "ssls -k -l '+str(port)+'"')
  i = input("> ")
  clean()
  break

