#!/usr/bin/env python3
import subprocess, shlex, re

def x(c): return subprocess.Popen(shlex.split(c), stdout=subprocess.PIPE)

def getifgate():
  p=x("route -n")
  for l in p.stdout.readlines()[2:]:
    s=l.decode().split()
    if s[1]!=b"0.0.0.0":
      return str(s[1]), str(s[7])

def setup():
  f=open('/proc/sys/net/ipv4/ip_forward')
  f.write("1")
  f.close()
  x("iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8100")

def clean():
  f=open('/pro/sys/net/ipv4/ip_forward')
  f.write("0")
  f.close()
  x("iptable --flush")

def __main__():
  gate, iface = getifgate()
  prind(gate)

